Numpy yra Numerical Python, trumpinasi np (import np). Galime kurti dimensijas. NumPy - pagrindine biblioteka skaiciavimams.
nd-array - masyvas - kuris laiko didelius duomenis. Duomenys turi būti homogenūs, t.y. vienodo tipo. 
dimensijos yra kelios: 1d, 2d, 3d, laiko dimensija
galima įsivertinti su shape. Kol kas iš formų ir stuktūrų žinome tik len (ilgis). dabar turime ir shape. axis 0, axis 1, axis 2.
Attributes of Numpy array - shape: a tuple indicating the size of each dimension. dtype: an object describing the data type of the array. 
Mokysimes traukti duomenis is ivairiu dimensiju. Array yra masyvas ir ka su juo galima daryti. Shape yra NumPy atributas, kuris nurodo masyvo matmen7 dydzius kiekvienoje asyje.
shape grazina tuple objekta. len(shape) nurodo kiek masyvas turi dimensiju.
NumPy arrays are fixed-size containers of items that are more efficient than Python lists or tuples for (...)
ndim - the number or dimensions(axes) in the array
shape - the size of the array for each dimension
size - the total number of elements in the array
dtype - the data type of elements in the array
Creating ndarray - jeigu reikalingos projekcijos ar skaiciavimai. ziuresim tutorial.
Numpy data tupes - int64, float64 - dazniausiai.
Linijines algebros funkcijos.
NumPy masyvai arrays ir ju savybes

In [1]:
import numpy as np

In [3]:
# Paprastas 1D masyvas (vienos dimensijos)
a = np.array([10, 20, 30, 40, 20, 50])
 
print("a =", a)
print("a.ndim  =", a.ndim)   # dimensijų skaičius
print("a.shape =", a.shape)  # forma
print("a.size  =", a.size)   # elementų kiekis
print("a.dtype =", a.dtype)  # duomenų tipas

a = [10 20 30 40 20 50]
a.ndim  = 1
a.shape = (6,)
a.size  = 6
a.dtype = int64


In [6]:
# 2D masyvas (dvi dimensijos, dažnai vadinamas matrica)
b = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(b)
print("b =\n", b)
print("b.ndim  =", b.ndim)
print("b.shape =", b.shape)  # 2 eilutės, 3 stulpeliai
print("b.size  =", b.size)   # 2 * 3 = 6 elementai
print("b.dtype =", b.dtype)

[[1 2 3]
 [4 5 6]]
b =
 [[1 2 3]
 [4 5 6]]
b.ndim  = 2
b.shape = (2, 3)
b.size  = 6
b.dtype = int64


In [7]:
#numpy parenka duomenu tipa, kuriame tilps viskas.
x = np.array([5, 10, 15])
y = np.array([[1, 2], [3, 4]])
 
print("x =", x)
print("y =\n", y)

x = [ 5 10 15]
y =
 [[1 2]
 [3 4]]


In [8]:
#np.ones yra masyvas uzpildytas vienetais
ones_1d = np.ones(5)        # 1D masyvas iš 5 vienetų
ones_2d = np.ones((2, 3))   # 2D masyvas: 2x3
 
print("ones_1d =", ones_1d)
print("ones_2d =\n", ones_2d)
print("ones_2d.dtype =", ones_2d.dtype)

ones_1d = [1. 1. 1. 1. 1.]
ones_2d =
 [[1. 1. 1.]
 [1. 1. 1.]]
ones_2d.dtype = float64


In [9]:
zeros_1d = np.zeros(4)
zeros_2d = np.zeros((3, 2))
 
print("zeros_1d =", zeros_1d)
print("zeros_2d =\n", zeros_2d)

zeros_1d = [0. 0. 0. 0.]
zeros_2d =
 [[0. 0.]
 [0. 0.]
 [0. 0.]]


In [10]:
np.zeros(3)
np.zeros((5,5))
np.ones(3)
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
seq1 = np.arange(0, 10)        # 0, 1, 2, ..., 9
seq2 = np.arange(2, 11, 2)     # 2, 4, 6, 8, 10
 
print("seq1 =", seq1)
print("seq2 =", seq2)

seq1 = [0 1 2 3 4 5 6 7 8 9]
seq2 = [ 2  4  6  8 10]


In [12]:
lin1 = np.linspace(0, 1, 5)      # 5 reikšmės nuo 0 iki 1
lin2 = np.linspace(10, 20, 3)    # 10, 15, 20
 
print("lin1 =", lin1)
print("lin2 =", lin2)

lin1 = [0.   0.25 0.5  0.75 1.  ]
lin2 = [10. 15. 20.]


In [13]:
# Pradinis 1D masyvas su 6 elementais
r = np.arange(1, 7)   # [1, 2, 3, 4, 5, 6]
 
print("r =", r)
print("r.shape =", r.shape)

r = [1 2 3 4 5 6]
r.shape = (6,)


In [14]:
# Formos pakeitimas į 2x3
r_2x3 = r.reshape(2, 3)
 
print("r_2x3 =\n", r_2x3)
print("r_2x3.shape =", r_2x3.shape)

r_2x3 =
 [[1 2 3]
 [4 5 6]]
r_2x3.shape = (2, 3)


In [15]:
a = np.array([10, 20, 30, 40, 50])
 
print("a =", a)
print("a[0]  =", a[0])   # pirmas elementas
print("a[2]  =", a[2])   # trečias elementas
print("a[-1] =", a[-1])  # paskutinis elementas
 

a = [10 20 30 40 50]
a[0]  = 10
a[2]  = 30
a[-1] = 50


In [16]:
b = np.array([
    [1,  2,  3],
    [4,  5,  6],
    [7,  8,  9]
])
 
print("b =\n", b)
print("b[0, 0] =", b[0, 0])   # 1 (pirma eilutė, pirmas stulpelis)
print("b[1, 2] =", b[1, 2])   # 6 (antra eilutė, trečias stulpelis)
print("b[-1, -1] =", b[-1, -1])  # 9 (paskutinė eilutė, paskutinis stulpelis)

b =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
b[0, 0] = 1
b[1, 2] = 6
b[-1, -1] = 9


In [17]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
 
print("x =", x)
print("x[2:6] =", x[2:6])      # elementai su indeksais 2,3,4,5
print("x[:4]  =", x[:4])       # nuo pradžios iki 4 (neįtraukiant)
print("x[5:]  =", x[5:])       # nuo 5 iki galo
print("x[::2] =", x[::2])      # kas antras elementas
print("x[::-1] =", x[::-1])    # apsukimas atgaline tvarka

x = [0 1 2 3 4 5 6 7 8 9]
x[2:6] = [2 3 4 5]
x[:4]  = [0 1 2 3]
x[5:]  = [5 6 7 8 9]
x[::2] = [0 2 4 6 8]
x[::-1] = [9 8 7 6 5 4 3 2 1 0]


In [18]:
p = np.array([1, 2, 3, 4])
q = np.array([10, 20, 30, 40])
 
print("p =", p)
print("q =", q)
 
print("p + q =", p + q)     # elementų suma
print("q - p =", q - p)     # elementų skirtumas
print("p * 2 =", p * 2)     # daugyba iš skaičiaus
print("q / 10 =", q / 10)   # dalyba iš skaičiaus (rezultatas dažnai tampa float)
 

p = [1 2 3 4]
q = [10 20 30 40]
p + q = [11 22 33 44]
q - p = [ 9 18 27 36]
p * 2 = [2 4 6 8]
q / 10 = [1. 2. 3. 4.]


In [19]:
values = np.array([3, 7, 2, 9, 5])
 
print("values =", values)
print("values > 5 =", values > 5)
print("values == 7 =", values == 7)

values = [3 7 2 9 5]
values > 5 = [False  True False  True False]
values == 7 = [False  True False False False]


In [20]:
values = np.array([3, 7, 2, 9, 5])
 
mask = values > 5
filtered = values[mask]
 
print("values =", values)
print("mask =", mask)
print("values[mask] =", filtered)

values = [3 7 2 9 5]
mask = [False  True False  True False]
values[mask] = [7 9]


In [21]:
values = np.array([3, 7, 2, 9, 5, 8, 1])
 
mask_between = (values >= 3) & (values <= 8)
print("values =", values)
print("mask_between =", mask_between)
print("values[mask_between] =", values[mask_between])

values = [3 7 2 9 5 8 1]
mask_between = [ True  True False False  True  True False]
values[mask_between] = [3 7 5 8]


In [22]:
m = np.array([10, 20, 30, 40, 50])
print("Pradinis m =", m)
 
m[1] = 999  # pakeičiama viena reikšmė pagal indeksą
print("Po m[1] = 999:", m)
 
m[m > 40] = 0  # pakeičiamos visos reikšmės, kurios tenkina sąlygą
print("Po m[m >= 40] = 0:", m)

Pradinis m = [10 20 30 40 50]
Po m[1] = 999: [ 10 999  30  40  50]
Po m[m >= 40] = 0: [10  0 30 40  0]


In [23]:
scores = np.array([40, 55, 70, 90, 30])
 
result = np.where(scores >= 60, "Pass", "Fail")
 
print("scores =", scores)
print("result =", result)

scores = [40 55 70 90 30]
result = ['Fail' 'Fail' 'Pass' 'Pass' 'Fail']


In [24]:
values = np.array([5, -2, 7, -1, 0])
 
# Neigiamas reikšmes pakeičia į 0, o kitas palieka kaip yra
non_negative = np.where(values < 0, 0, values)
 
print("values =", values)
print("non_negative =", non_negative)

values = [ 5 -2  7 -1  0]
non_negative = [5 0 7 0 0]


In [25]:
data = np.array([2, 4, 6, 8, 10])
 
print("data =", data)
print("sum  =", data.sum())
print("mean =", data.mean())
print("min  =", data.min())
print("max  =", data.max())
print("std  =", data.std())

data = [ 2  4  6  8 10]
sum  = 30
mean = 6.0
min  = 2
max  = 10
std  = 2.8284271247461903


In [26]:
mat = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
 
print("mat =\n", mat)
print("Suma pagal stulpelius (axis=0):", mat.sum(axis=0))  # [1+4, 2+5, 3+6]
print("Suma pagal eilutes (axis=1):", mat.sum(axis=1))    # [1+2+3, 4+5+6]

mat =
 [[1 2 3]
 [4 5 6]]
Suma pagal stulpelius (axis=0): [5 7 9]
Suma pagal eilutes (axis=1): [ 6 15]


In [27]:
arr = np.array([3, 1, 2, 3, 2, 2, 5])
 
print("arr =", arr)
print("unique =", np.unique(arr))
print("sorted =", np.sort(arr))

arr = [3 1 2 3 2 2 5]
unique = [1 2 3 5]
sorted = [1 2 2 2 3 3 5]


In [28]:
vals = np.array([-5, 0, 3, 10, 15])
 
# Apriboja reikšmes intervale [0, 10]
clipped = np.clip(vals, 0, 10)
 
print("vals =", vals)
print("clipped =", clipped)

vals = [-5  0  3 10 15]
clipped = [ 0  0  3 10 10]


In [29]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5])
 
combined = np.concatenate([a1, a2])
 
print("a1 =", a1)
print("a2 =", a2)
print("combined =", combined)

a1 = [1 2 3]
a2 = [4 5]
combined = [1 2 3 4 5]


In [30]:
mat = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
 
add_row = np.array([10, 20, 30])  # forma (3,)
 
# Vektorius pridedamas prie kiekvienos eilutės (eilutė po eilutės)
result = mat + add_row
 
print("mat =\n", mat)
print("add_row =", add_row)
print("mat + add_row =\n", result)
 

mat =
 [[1 2 3]
 [4 5 6]]
add_row = [10 20 30]
mat + add_row =
 [[11 22 33]
 [14 25 36]]


In [31]:
A = np.array([
    [1, 2],
    [3, 4]
])
 
B = np.array([
    [10, 20],
    [30, 40]
])
 
print("A =\n", A)
print("B =\n", B)
 
# Elementų lygio sudėtis ir daugyba
print("A + B =\n", A + B)
print("A * B (element-wise) =\n", A * B)

A =
 [[1 2]
 [3 4]]
B =
 [[10 20]
 [30 40]]
A + B =
 [[11 22]
 [33 44]]
A * B (element-wise) =
 [[ 10  40]
 [ 90 160]]


In [32]:
# Matricų sandauga su @
A = np.array([
    [1, 2],
    [3, 4]
])
 
B = np.array([
    [10, 20],
    [30, 40]
])
 
print("A @ B =\n", A @ B)

A @ B =
 [[ 70 100]
 [150 220]]


In [33]:
M = np.array([
    [2, 4, 6],
    [1, 3, 5]
])
 
print("M =\n", M)
print("M * 10 =\n", M * 10)
print("M + 1 =\n", M + 1)

M =
 [[2 4 6]
 [1 3 5]]
M * 10 =
 [[20 40 60]
 [10 30 50]]
M + 1 =
 [[3 5 7]
 [2 4 6]]


In [34]:
M = np.array([
    [2, 4, 6],
    [1, 3, 5]
])
 
print("M =\n", M)
print("M.T =\n", M.T)
print("M.shape =", M.shape)
print("M.T.shape =", M.T.shape)

M =
 [[2 4 6]
 [1 3 5]]
M.T =
 [[2 1]
 [4 3]
 [6 5]]
M.shape = (2, 3)
M.T.shape = (3, 2)


In [35]:
vals = np.array([-2.7, -1.2, 0.0, 1.4, 3.9])
 
print("vals =", vals)
print("abs =", np.abs(vals))
print("round(1) =", np.round(vals))
print("clip [0, 3] =", np.clip(vals, 0, 3))

vals = [-2.7 -1.2  0.   1.4  3.9]
abs = [2.7 1.2 0.  1.4 3.9]
round(1) = [-3. -1.  0.  1.  4.]
clip [0, 3] = [0.  0.  0.  1.4 3. ]


In [36]:
pos = np.array([1, 4, 9, 16])
 
print("pos =", pos)
print("sqrt =", np.sqrt(pos))
print("log =", np.log(pos))
print("exp =", np.exp(np.array([0, 1, 2])))

pos = [ 1  4  9 16]
sqrt = [1. 2. 3. 4.]
log = [0.         1.38629436 2.19722458 2.77258872]
exp = [1.         2.71828183 7.3890561 ]


In [37]:
data = np.array([5, 2, 9, 1, 7])
 
print("data =", data)
print("sum =", data.sum())
print("mean =", data.mean())
print("min =", data.min())
print("max =", data.max())
print("median =", np.median(data))
print("std =", data.std())
print("var =", data.var())

data = [5 2 9 1 7]
sum = 24
mean = 4.8
min = 1
max = 9
median = 5.0
std = 2.9933259094191533
var = 8.96


In [38]:
mat = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
 
print("mat =\n", mat)
print("Vidurkis pagal stulpelius (axis=0):", mat.mean(axis=0))
print("Vidurkis pagal eilutes (axis=1):", mat.mean(axis=1))

mat =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Vidurkis pagal stulpelius (axis=0): [4. 5. 6.]
Vidurkis pagal eilutes (axis=1): [2. 5. 8.]


In [39]:
scores = np.array([40, 55, 70, 90, 30])
 
passed = scores >= 60
 
print("scores =", scores)
print("passed =", passed)
 
print("any passed =", passed.any())
print("all passed =", passed.all())
print("passed count =", passed.sum())

scores = [40 55 70 90 30]
passed = [False False  True  True False]
any passed = True
all passed = False
passed count = 2


In [40]:
prices = np.array([9.99, 14.50, 3.20, 25.00, 7.80])
 
mask = prices > 10
high_prices = prices[mask]
 
print("prices =", prices)
print("mask =", mask)
print("high_prices =", high_prices)
print("high_prices count =", mask.sum())
print("high_prices mean =", high_prices.mean())

prices = [ 9.99 14.5   3.2  25.    7.8 ]
mask = [False  True False  True False]
high_prices = [14.5 25. ]
high_prices count = 2
high_prices mean = 19.75


In [41]:
a = np.arange(1, 13)  # 1..12
print("a =", a)
print("a.shape =", a.shape)
print("a.size =", a.size)

a = [ 1  2  3  4  5  6  7  8  9 10 11 12]
a.shape = (12,)
a.size = 12


In [42]:
# Formos pakeitimas į 3x4
a_3x4 = a.reshape(3, 4)
print("a_3x4 =\n", a_3x4)
print("a_3x4.shape =", a_3x4.shape)

a_3x4 =
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
a_3x4.shape = (3, 4)


In [43]:
# Automatinis vienos dimensijos parinkimas su -1
a_auto = a.reshape(2, -1)   # 2 eilutės, stulpelių skaičius apskaičiuojamas automatiškai
print("a_auto =\n", a_auto)
print("a_auto.shape =", a_auto.shape)

a_auto =
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
a_auto.shape = (2, 6)


In [44]:
m = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
 
flat = m.flatten()
rav = m.ravel()
 
print("m =\n", m)
print("flatten() =", flat)
print("ravel()   =", rav)

m =
 [[1 2 3]
 [4 5 6]]
flatten() = [1 2 3 4 5 6]
ravel()   = [1 2 3 4 5 6]


In [45]:
# Pavyzdys, kaip keitimas gali elgtis skirtingai
m = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
 
flat = m.flatten()
rav = m.ravel()
 
flat[0] = 999
rav[1] = 888
 
print("Po pakeitimų:")
print("m =\n", m)          # ravel pakeitimas dažnai persiduoda į originalą
print("flat =", flat)      # flatten yra atskira kopija
print("rav  =", rav)
 

Po pakeitimų:
m =
 [[  1 888   3]
 [  4   5   6]]
flat = [999   2   3   4   5   6]
rav  = [  1 888   3   4   5   6]


In [46]:
arr = np.arange(1, 13)  # 1..12
 
parts = np.split(arr, 3)  # 12 elementų dalinami į 3 lygias dalis po 4
 
print("arr =", arr)
print("split į 3 dalis:")
for i, p in enumerate(parts, start=1):
    print(f"  dalis {i}:", p)

arr = [ 1  2  3  4  5  6  7  8  9 10 11 12]
split į 3 dalis:
  dalis 1: [1 2 3 4]
  dalis 2: [5 6 7 8]
  dalis 3: [ 9 10 11 12]
